FROM openjdk:11.0.7-jre

ARG JAR_FILE
ADD ${JAR_FILE} service.jar

# Reference is from https://github.com/redboxllc/scuttle
# which fixes the issue of CronJobs not exiting with an Istio sidecar
COPY --from=redboxoss/scuttle:latest /scuttle /bin/scuttle

ENTRYPOINT ["scuttle", "java", "-jar", "service.jar"]