server:
  port: 9000

spring:
  devtools:
    add-properties: false
  jpa:
    hibernate:
      ddl: validate
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/otps}
    username: ${SPRING_DATASOURCE_USERNAME:otp}
    password: ${SPRING_DATASOURCE_PASSWORD:otp-pass}

logging:
  level:
    root: INFO

otp:
  key: ${OTP_SECRET:testkey}
