logging:
  level:
    root: DEBUG

spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:tcp://localhost:1521/jobs;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:jobs}
    password: ${SPRING_DATASOURCE_PASSWORD:jobs-pass}
