spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/users}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:user-pass}

  #  liquibase:
  #    change-log: classpath:liquibase/master.yaml
  #    enabled: true

  flyway:
    locations: classpath:db/migration

logging:
  level:
    root: INFO
