server:
  port: 9090

spring:
  batch:
    initialize-schema: ${SPRING_BATCH_INITIALIZE_SCHEMA:always}
    job:
      names: ${SPRING_BATCH_JOB_NAMES:none}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
  main:
    web-application-type: none
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/users}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:user-pass}

datasource:
  jobs:
    url: ${BATCH_DATABASE_URL:jdbc:postgresql://localhost:5434/jobs}
    username: ${BATCH_DATABASE_USERNAME:jobs}
    password: ${BATCH_DATABASE_PASSWORD:jobs-pass}

logging:
  level:
    root: ${LOGLEVEL:INFO}

verifyEndpoint: ${VERIFY_ENDPOINT:http://localhost:9090/api/user-service/v1/verify}
testEmail: ${TEST_EMAIL:garihubtest@gmail.com}

services:
  email:
    url: ${EMAIL_URL:http://localhost:6000/api/v1/mail/}

  sms:
    url: ${SMS_URL:http://localhost:8080/api/v1/sms/}
