spring:
  devtools:
    add-properties: true

logging:
  level:
    root: DEBUG

datasource:
  jobs:
    driver-class-name: ${BATCH_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${BATCH_DATABASE_URL:jdbc:h2:tcp://localhost:1521/jobs;DB_CLOSE_DELAY=-1}
    # You can use this, if you don't want to start up the H2 DB
    # url: ${BATCH_DATABASE_URL:jdbc:h2:mem:jobs;DB_CLOSE_DELAY=-1}
    username: ${BATCH_DATABASE_USERNAME:jobs}
    password: ${BATCH_DATABASE_PASSWORD:jobs-pass}
