package com.garihub.user.core

typealias UserIdentifier = String
// this is the external identifier not generated by this service, but generated by the AuthService
typealias UserExternalIdentifier = String
typealias VerificationToken = String
typealias EmailAddress = String
