apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-api-vs
  namespace: usermgt
spec:
  hosts:
    - "*"
  gateways:
    - default/garihub-gateway
  http:
    - name: garihub-user-api
      match:
        - uri:
            prefix: /api/user-service/v1/
      route:
        - destination:
            host: user-svc
            port:
              number: 9090
