# There is currently an issue with Istio with CronJobs
# https://github.com/istio/istio/issues/11659
# Possible fixes are to use the following:
# Ref: https://stackoverflow.com/questions/54921054/terminate-istio-sidecar-istio-proxy-for-a-kubernetes-job-cronjob
# Ref: https://medium.com/redbox-techblog/handling-istio-sidecars-in-kubernetes-jobs-c392661c4af7
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
# Ref: https://github.com/redboxllc/scuttle
# Ref: https://github.com/monzo/envoy-preflight

# The current implementation uses https://github.com/redboxllc/scuttle to fix this issue
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: usermgt
  name: send-verification-email
#  Use this to disable Istio sidecar Injection in a pod
#  annotations: &Annotations
#    sidecar.istio.io/inject: 'false'
  labels: &UserApi
    app: user-api
    role: cron
    stack: backend
    tier: user-mgt
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      template:
        metadata:
#          annotations: *Annotations
          labels: *UserApi
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: docker-hub-registry

          containers:
            - name: send-user-verification-email
              image: garihublimited/user-service-jobs
              imagePullPolicy: Always
              env:
                - name: SPRING_BATCH_JOB_NAMES
                  value: sendVerificationEmailJob

                - name: DEBUG
                  value: "false"

                - name: SPRING_DATASOURCE_URL
                  valueFrom:
                    secretKeyRef:
                      name: user-api-db
                      key: url_pool

                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: user-api-db
                      key: username

                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: user-api-db
                      key: password

                - name: BATCH_DRIVER_CLASS_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: user-api-config
                      key: driver_class

                - name: BATCH_DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: user-api-db
                      key: url_jobs_pool

                - name: BATCH_DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: user-api-db
                      key: username

                - name: BATCH_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: user-api-db
                      key: password

                - name: SPRING_PROFILES_ACTIVE
                  valueFrom:
                    configMapKeyRef:
                      name: user-api-config
                      key: profile

                - name: VERIFY_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: user-api-config
                      key: verify_endpoint

                - name: EMAIL_URL
                  valueFrom:
                    configMapKeyRef:
                      name: user-api-config
                      key: email_url

                - name: SMS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: user-api-config
                      key: email_url

                # Reference: https://github.com/redboxllc/scuttle

                - name: ISTIO_QUIT_API
                  value: http://127.0.0.1:15020

                - name: ENVOY_ADMIN_API
                  value: http://127.0.0.1:15000
