package com.garihub.user.core.models

import com.garihub.user.core.UserIdentifier

/**
 * Representation of a User in the platform
 * @property identifier [UserIdentifier] Unique identifier for this user. Only NULL when creating a user.
 * Other usecases should have this defined. This is generated by this application
 * @property externalIdentifier [UserIdentifier] Unique identifier for this user as is identified by the Auth Server.
 * Only NULL when creating a user. Other usecases should have this defined once a user has been verified
 * @property firstName [String] First name of this user
 * @property lastIndex [String] User's last name
 * @property gender [Gender] User's gender
 * @property phoneNumber [String] User's phone number
 * @property emailAddress [String] User's email address
 * @property userType [UserType] User type
 * @property password [String] User's password
 */
data class User(
    val identifier: UserIdentifier? = null,
    val externalIdentifier: UserIdentifier? = null,
    val firstName: String,
    val lastName: String,
    val gender: Gender,
    val phoneNumber: String,
    val emailAddress: String,
    val userType: UserType,
    val password: String? = null
)
