# Ref: https://github.com/wangchucheng/git-repo-sync
name: BitBucket RepoSync

on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Bitbucket Repo Sync
    steps:

      # Ref: https://github.com/actions/checkout
      -   uses: actions/checkout@v3
          with:
            fetch-depth: 0

      -   name: Mirror to Bitbucket
          uses: wangchucheng/git-repo-sync@v0.1.0
          with:
            target-url: ${{ secrets.BITBUCKET_REPO_URL }}
            target-username: ${{ secrets.BITBUCKET_USERNAME }}
            target-token: ${{ secrets.BITBUCKET_ACCESS_TOKEN }}