# Ref: https://github.com/wangchucheng/git-repo-sync
name: Gitlab RepoSync

on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Gitlab Repo Sync
    steps:

      # Ref: https://github.com/actions/checkout
      -   uses: actions/checkout@v3
          with:
            fetch-depth: 0

      -   name: Mirror to Gitlab
          uses: wangchucheng/git-repo-sync@v0.1.0
          with:
            target-url: ${{ secrets.GITLAB_REPO_URL }}
            target-username: ${{ secrets.GITLAB_USERNAME }}
            target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
